name: Release
on:
  push:
    tags:
      - '**@[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn

      - name: npm auth setup
        run: |
          yarn logout
          echo "//registry.npmjs.org/:_authToken=$NPM_RELEASE_AUTH_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_RELEASE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_AUTH_TOKEN }}

      - name: Publish to NPM
        run: yarn release:publish
